const ENTITIES = [
  {
    name: "Venture Kick",
    type: "Incubator",
    location: "Switzerland",
    investments: 1354,
    sectors: ["Tech", "AI", "SaaS"],
    app_start: "2026-02-01",
    app_end: "2026-05-30",
    is_rolling: false,
    description: "Swiss startup support initiative focused on research-driven ventures.",
    apply_url: "https://www.venturekick.ch/"
  },
  {
    name: "TIPS Program",
    type: "Incubator",
    location: "South Korea",
    investments: 1232,
    sectors: ["Tech", "DeepTech"],
    app_start: "2026-01-15",
    app_end: "2026-06-01",
    is_rolling: false,
    description: "Government-backed startup acceleration and R&D commercialization support.",
    apply_url: "https://www.k-startup.go.kr/"
  },
  {
    name: "VentureOut",
    type: "Incubator",
    location: "United States",
    investments: 1095,
    sectors: ["Tech", "SaaS", "AI"],
    app_start: "2026-04-01",
    app_end: "2026-05-01",
    is_rolling: false,
    description: "Program helping startups expand globally through market-entry support.",
    apply_url: "https://ventureoutny.com/"
  },
  {
    name: "Maine Technology Institute",
    type: "Incubator",
    location: "United States",
    investments: 715,
    sectors: ["HealthTech", "Energy", "Tech"],
    app_start: "2026-02-10",
    app_end: "2026-07-15",
    is_rolling: false,
    description: "Seed funding and commercialization support for innovation-led companies.",
    apply_url: "https://www.mainetechnology.org/"
  },
  {
    name: "Innovation Works",
    type: "Incubator",
    location: "United States",
    investments: 631,
    sectors: ["Tech", "Robotics", "AI"],
    app_start: "2026-03-15",
    app_end: "2026-09-30",
    is_rolling: false,
    description: "Early-stage investor and incubator backing software and hard-tech founders.",
    apply_url: "https://www.innovationworks.org/"
  },
  {
    name: "AGORANOV",
    type: "Incubator",
    location: "France",
    investments: 438,
    sectors: ["DeepTech", "HealthTech", "SaaS"],
    app_start: "2026-01-10",
    app_end: "2026-04-25",
    is_rolling: false,
    description: "Paris-based incubator for science and technology-led startups.",
    apply_url: "https://www.agoranov.com/"
  },
  {
    name: "Venture Catalysts",
    type: "Incubator",
    location: "India",
    investments: 415,
    sectors: ["Fintech", "D2C", "SaaS"],
    app_start: "2026-02-20",
    app_end: "2026-05-05",
    is_rolling: false,
    description: "India-focused startup platform combining investment and growth mentorship.",
    apply_url: "https://venturecatalysts.in/"
  },
  {
    name: "Thrive Capital",
    type: "VC",
    location: "United States",
    investments: 355,
    sectors: ["AI", "Fintech", "Consumer"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Venture fund investing in category-defining technology companies.",
    apply_url: "https://thrivecap.com/"
  },
  {
    name: "Tenity",
    type: "Incubator",
    location: "Switzerland",
    investments: 319,
    sectors: ["Fintech", "Insurtech", "AI"],
    app_start: "2026-03-01",
    app_end: "2026-04-20",
    is_rolling: false,
    description: "Global innovation ecosystem focused on fintech and enterprise innovation.",
    apply_url: "https://www.tenity.com/"
  },
  {
    name: "IIT Mandi Catalyst",
    type: "Incubator",
    location: "India",
    investments: 314,
    sectors: ["DeepTech", "AI", "SaaS"],
    app_start: "2026-01-20",
    app_end: "2026-05-20",
    is_rolling: false,
    description: "Technology business incubator supporting founders from idea to scale.",
    apply_url: "https://www.catalystiitmandi.com/"
  },
  {
    name: "Sting",
    type: "Incubator",
    location: "Sweden",
    investments: 309,
    sectors: ["Climate", "HealthTech", "AI"],
    app_start: "2026-04-01",
    app_end: "2026-05-25",
    is_rolling: false,
    description: "Stockholm innovation hub for high-growth startups in impact sectors.",
    apply_url: "https://www.sting.co/"
  },
  {
    name: "DMZ",
    type: "Incubator",
    location: "Canada",
    investments: 278,
    sectors: ["Tech", "SaaS", "Fintech"],
    app_start: "2026-02-01",
    app_end: "2026-04-18",
    is_rolling: false,
    description: "University-backed startup ecosystem with global market access support.",
    apply_url: "https://dmz.torontomu.ca/"
  },
  {
    name: "TechNexus Venture Collaborative",
    type: "Incubator",
    location: "United States",
    investments: 260,
    sectors: ["Enterprise", "AI", "SaaS"],
    app_start: "2026-03-12",
    app_end: "2026-06-15",
    is_rolling: false,
    description: "Corporate innovation model linking startups and enterprise partners.",
    apply_url: "https://technexus.com/"
  },
  {
    name: "Velocity",
    type: "Incubator",
    location: "Canada",
    investments: 258,
    sectors: ["Hardware", "AI", "HealthTech"],
    app_start: "2026-03-05",
    app_end: "2026-04-28",
    is_rolling: false,
    description: "Founder-first startup hub helping scale hardware and software ventures.",
    apply_url: "https://velocityincubator.com/"
  },
  {
    name: "tech2b Inkubator",
    type: "Incubator",
    location: "Austria",
    investments: 256,
    sectors: ["DeepTech", "AI", "Industrial"],
    app_start: "2026-02-15",
    app_end: "2026-05-18",
    is_rolling: false,
    description: "Austrian incubator for technology-driven and science-based startups.",
    apply_url: "https://www.tech2b.at/"
  },
  {
    name: "Eurasante",
    type: "Incubator",
    location: "France",
    investments: 237,
    sectors: ["HealthTech", "BioTech", "MedTech"],
    app_start: "2026-01-01",
    app_end: "2026-04-16",
    is_rolling: false,
    description: "Health innovation ecosystem supporting biotech and medtech founders.",
    apply_url: "https://www.eurasante.com/"
  },
  {
    name: "SAP.iO",
    type: "Incubator",
    location: "United States",
    investments: 234,
    sectors: ["Enterprise", "AI", "B2B SaaS"],
    app_start: "2026-03-01",
    app_end: "2026-08-10",
    is_rolling: false,
    description: "Strategic startup program connecting B2B ventures with SAP customers.",
    apply_url: "https://sap.io/"
  },
  {
    name: "EvoNexus",
    type: "Incubator",
    location: "United States",
    investments: 228,
    sectors: ["DeepTech", "Cybersecurity", "AI"],
    app_start: "2026-02-01",
    app_end: "2026-04-23",
    is_rolling: false,
    description: "Southern California incubator focused on frontier and deep technology startups.",
    apply_url: "https://evonexus.org/"
  },
  {
    name: "Cyberport Hong Kong",
    type: "Incubator",
    location: "Hong Kong",
    investments: 194,
    sectors: ["Fintech", "Smart City", "AI"],
    app_start: "2026-01-20",
    app_end: "2026-05-30",
    is_rolling: false,
    description: "Digital technology ecosystem supporting startup growth across Asia.",
    apply_url: "https://www.cyberport.hk/"
  },
  {
    name: "Y Combinator",
    type: "Accelerator",
    location: "United States",
    investments: null,
    sectors: ["Tech", "AI", "Fintech", "SaaS"],
    app_start: "2026-04-01",
    app_end: "2026-05-04",
    is_rolling: false,
    description: "Top accelerator known for backing Airbnb, Dropbox, Reddit, and more.",
    apply_url: "https://www.ycombinator.com/apply",
    verification_status: "verified",
    last_verified_at: "2026-04-15",
    source_url: "https://www.ycombinator.com/apply"
  },
  {
    name: "Techstars",
    type: "Accelerator",
    location: "United States / Global",
    investments: null,
    sectors: ["Tech", "SaaS", "Fintech"],
    app_start: "2026-03-15",
    app_end: "2026-06-02",
    is_rolling: false,
    description: "Global accelerator network operating in more than 50 cities.",
    apply_url: "https://www.techstars.com/"
  },
  {
    name: "500 Global",
    type: "Accelerator",
    location: "United States",
    investments: null,
    sectors: ["Fintech", "MarTech", "SaaS"],
    app_start: "2026-03-20",
    app_end: "2026-05-15",
    is_rolling: false,
    description: "Early-stage accelerator and fund with global startup programs.",
    apply_url: "https://500.co/"
  },
  {
    name: "Entrepreneur First",
    type: "Accelerator",
    location: "United Kingdom",
    investments: null,
    sectors: ["DeepTech", "AI", "SaaS"],
    app_start: null,
    app_end: null,
    is_rolling: false,
    description: "Pre-team accelerator that helps exceptional individuals build companies.",
    apply_url: "https://www.joinef.com/",
    deadlines: [
      {
        label: "Europe Bridge Residency (Summer 2026)",
        app_start: null,
        app_end: "2026-06-01",
        is_rolling: false
      },
      {
        label: "London Program (Fall 2026, Early)",
        app_start: null,
        app_end: "2026-05-10",
        is_rolling: false
      },
      {
        label: "Bangalore Program (Fall 2026, Early)",
        app_start: null,
        app_end: "2026-05-01",
        is_rolling: false
      },
      {
        label: "US Funding & Fellowships",
        app_start: null,
        app_end: null,
        is_rolling: true
      }
    ]
  },
  {
    name: "Startupbootcamp",
    type: "Accelerator",
    location: "United Kingdom / Global",
    investments: null,
    sectors: ["Fintech", "HealthTech", "Smart City"],
    app_start: "2026-01-25",
    app_end: "2026-05-10",
    is_rolling: false,
    description: "Industry-specific accelerator programs with global mentor networks.",
    apply_url: "https://www.startupbootcamp.org/"
  },
  {
    name: "Rockstart",
    type: "Accelerator",
    location: "Netherlands",
    investments: null,
    sectors: ["Energy", "HealthTech", "AgriFood"],
    app_start: "2026-02-20",
    app_end: "2026-05-05",
    is_rolling: false,
    description: "Impact-driven accelerator focused on energy, health, and agrifood startups.",
    apply_url: "https://rockstart.com/"
  },
  {
    name: "Antler",
    type: "Accelerator",
    location: "Singapore",
    investments: null,
    sectors: ["Tech", "AI", "SaaS"],
    app_start: "2026-03-01",
    app_end: "2026-06-20",
    is_rolling: false,
    description: "Day-zero investor and company builder for early-stage founders.",
    apply_url: "https://www.antler.co/"
  },
  {
    name: "SparkLabs",
    type: "Accelerator",
    location: "South Korea",
    investments: null,
    sectors: ["Tech", "SaaS", "Global Expansion"],
    app_start: "2026-04-05",
    app_end: "2026-06-30",
    is_rolling: false,
    description: "Korean accelerator helping startups scale into international markets.",
    apply_url: "https://www.sparklabs.co.kr/"
  },
  {
    name: "AppWorks",
    type: "Accelerator",
    location: "Taiwan",
    investments: null,
    sectors: ["AI", "Blockchain", "SaaS"],
    app_start: "2026-02-01",
    app_end: "2026-04-27",
    is_rolling: false,
    description: "Founder community and accelerator focused on AI and blockchain startups.",
    apply_url: "https://www.appworks.tw/"
  },
  {
    name: "Flat6Labs",
    type: "Accelerator",
    location: "Egypt",
    investments: null,
    sectors: ["Tech", "Fintech", "D2C"],
    app_start: "2026-01-15",
    app_end: "2026-04-24",
    is_rolling: false,
    description: "MENA-focused accelerator and seed investor for regional founders.",
    apply_url: "https://flat6labs.com/"
  },
  {
    name: "Start-Up Chile",
    type: "Accelerator",
    location: "Chile",
    investments: null,
    sectors: ["Tech", "Impact", "SaaS"],
    app_start: "2026-03-10",
    app_end: "2026-05-08",
    is_rolling: false,
    description: "Public accelerator attracting global startups to build in Chile.",
    apply_url: "https://startupchile.org/"
  },
  {
    name: "India Accelerator",
    type: "Accelerator",
    location: "India",
    investments: null,
    sectors: ["Sector Agnostic", "Tech", "SaaS"],
    app_start: "2026-02-05",
    app_end: "2026-04-21",
    is_rolling: false,
    description: "India-focused accelerator supporting startups from validation to growth.",
    apply_url: "https://www.indiaaccelerator.co/"
  },
  {
    name: "SBIR/STTR Grants",
    type: "Grants",
    location: "United States",
    investments: null,
    sectors: ["DeepTech", "HealthTech", "AI"],
    app_start: "2026-01-01",
    app_end: "2026-06-30",
    is_rolling: false,
    description: "US federal R&D grants for small businesses through agency-specific tracks.",
    apply_url: "https://www.sbir.gov/"
  },
  {
    name: "Horizon Europe EIC Accelerator",
    type: "Grants",
    location: "European Union",
    investments: null,
    sectors: ["Climate", "DeepTech", "HealthTech"],
    app_start: "2026-02-01",
    app_end: "2026-05-20",
    is_rolling: false,
    description: "EU funding program supporting breakthrough and scalable innovations.",
    apply_url: "https://eic.ec.europa.eu/eic-funding-opportunities/eic-accelerator_en"
  },
  {
    name: "Innovate UK Smart Grants",
    type: "Grants",
    location: "United Kingdom",
    investments: null,
    sectors: ["AI", "SaaS", "Industrial"],
    app_start: "2026-03-10",
    app_end: "2026-06-15",
    is_rolling: false,
    description: "UK innovation grants for game-changing R&D projects across sectors.",
    apply_url: "https://www.ukri.org/councils/innovate-uk/"
  },
  {
    name: "Startup India Seed Fund Scheme",
    type: "Grants",
    location: "India",
    investments: null,
    sectors: ["Tech", "Fintech", "D2C"],
    app_start: "2026-01-20",
    app_end: "2026-07-01",
    is_rolling: false,
    description: "Government-backed seed support for early-stage Indian startups.",
    apply_url: "https://seedfund.startupindia.gov.in/"
  },
  {
    name: "Singapore Enterprise Development Grant",
    type: "Grants",
    location: "Singapore",
    investments: null,
    sectors: ["Tech", "SaaS", "Global Expansion"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Grant support for capability building, innovation, and market access.",
    apply_url: "https://www.enterprisesg.gov.sg/financial-support/grants/for-local-companies/enterprise-development-grant"
  },
  {
    name: "Amazon Saheli Accelerate Season 2",
    type: "Accelerator",
    location: "India",
    investments: null,
    sectors: ["D2C", "Women", "E-commerce"],
    app_start: null,
    app_end: "2026-04-16",
    is_rolling: false,
    description: "Free accelerator for women-led businesses with Amazon mentorship and demo day support.",
    apply_url: "https://www.startupindia.gov.in/bodo/content/sih/en/ams-application/accelerator-program.html?applicationId=690b081ee4b06dfd0cb01970"
  },
  {
    name: "Innovate for Impact Challenge 2026",
    type: "Grants",
    location: "Global",
    investments: null,
    sectors: ["AgriTech", "Agriculture", "Food Security"],
    app_start: null,
    app_end: "2026-04-16",
    is_rolling: false,
    description: "Global challenge offering up to $50,000 for early-stage agtech solutions.",
    apply_url: "https://my.reviewr.com/s2/site/Innovate_for_Impact_Challenge_2026"
  },
  {
    name: "BioNEST Incubation Program - FITT IIT Delhi",
    type: "Incubator",
    location: "India",
    investments: null,
    sectors: ["BioTech", "HealthTech", "Medical Devices"],
    app_start: null,
    app_end: "2026-04-16",
    is_rolling: false,
    description: "Biotech incubation at IIT Delhi for idea to early prototype stage innovators.",
    apply_url: "https://accubate.fitt-iitd.in/ext/form/3403/1/apply"
  },
  {
    name: "Cohort 7 Incubation Program at VJTI TBI Foundation",
    type: "Incubator",
    location: "India",
    investments: null,
    sectors: ["Energy", "EV", "Semiconductors", "AI"],
    app_start: null,
    app_end: "2026-04-18",
    is_rolling: false,
    description: "Incubation cohort for startups in energy, EV, semiconductors, AI/ML, and cybersecurity.",
    apply_url: "https://www.startupindia.gov.in/content/sih/en/ams-application/incubator-program.html?applicationId=69bfa088e4b0b7e5b731e883"
  },
  {
    name: "Google for Startups Accelerator: India",
    type: "Accelerator",
    location: "India",
    investments: null,
    sectors: ["AI", "ML", "SaaS"],
    app_start: null,
    app_end: "2026-04-20",
    is_rolling: false,
    description: "Equity-free accelerator for AI-first Indian startups from Seed to Series A.",
    apply_url: "https://docs.google.com/forms/d/e/1FAIpQLSe7aNTQze5Rcbkl22Igo2IVtPgRkfS0wXyWH3HXOJsW9ELSwA/viewform"
  },
  {
    name: "iAccelerate Batch 2",
    type: "Accelerator",
    location: "India",
    investments: null,
    sectors: ["DeepTech", "AI", "Tier 2/3"],
    app_start: null,
    app_end: "2026-04-21",
    is_rolling: false,
    description: "Deep tech accelerator for startups in Tamil Nadu's Tier 2 and Tier 3 cities.",
    apply_url: "https://forms.office.com/Pages/ResponsePage.aspx?id=FiJzfN84RUmX7-JGPD7wyo_XpwvEQVtEldnmCA2NyOVUMDBHM01SSDRWM1Q5OE5BRFFSMFhPSlNXTy4u"
  },
  {
    name: "FITT IIT Delhi - BIRAC LEAP Fund",
    type: "Grants",
    location: "India",
    investments: null,
    sectors: ["BioTech", "MedTech", "HealthTech"],
    app_start: null,
    app_end: "2026-04-21",
    is_rolling: false,
    description: "Funding support up to INR 70L for biotech and medtech startups.",
    apply_url: "https://accubate.fitt-iitd.in/ext/form/23438/1/apply"
  },
  {
    name: "Global Arts Prize for Innovation (GAP)",
    type: "Grants",
    location: "Global",
    investments: null,
    sectors: ["Arts", "Culture", "Creative Economy"],
    app_start: null,
    app_end: "2026-04-21",
    is_rolling: false,
    description: "Prize competition recognizing ventures redefining contemporary culture.",
    apply_url: "https://www.globalleadersinstitute.org/gap/"
  },
  {
    name: "UDAAN Drone Acceleration Program - SIIC IIT Kanpur",
    type: "Accelerator",
    location: "India",
    investments: null,
    sectors: ["Drones", "UAV", "DeepTech"],
    app_start: null,
    app_end: "2026-04-26",
    is_rolling: false,
    description: "Acceleration plus fellowship support for DPIIT-registered drone startups.",
    apply_url: "https://connect.siicincubator.com/udaan/applications"
  },
  {
    name: "Healthcare Incubation Program - NSRCEL IIM Bangalore",
    type: "Incubator",
    location: "India",
    investments: null,
    sectors: ["HealthTech", "MedTech", "Healthcare"],
    app_start: null,
    app_end: "2026-04-27",
    is_rolling: false,
    description: "Incubation for Indian healthcare startups with mentors and partner access.",
    apply_url: "https://nsrcel.accubate.app/ext/form/3384/1/apply"
  },
  {
    name: "WEnnovate 2.0",
    type: "Accelerator",
    location: "India",
    investments: null,
    sectors: ["Women", "DeepTech", "AI"],
    app_start: null,
    app_end: "2026-04-30",
    is_rolling: false,
    description: "Acceleration track for women-led deeptech startups under two years old.",
    apply_url: "https://forms.gle/6aD2BFBrg1vpopaRA"
  },
  {
    name: "O'Shaughnessy Fellowships and Grants",
    type: "Grants",
    location: "Global",
    investments: null,
    sectors: ["Fellowship", "General", "Innovation"],
    app_start: null,
    app_end: "2026-05-01",
    is_rolling: false,
    description: "Fellowship and grant support for ambitious builders and researchers.",
    apply_url: "https://www.osvfellowship.com/"
  },
  {
    name: "DST NIDHI Seed Support Program - ACIC VGU Foundation",
    type: "Grants",
    location: "India",
    investments: null,
    sectors: ["Seed Funding", "Tech", "DPIIT"],
    app_start: null,
    app_end: "2026-05-01",
    is_rolling: false,
    description: "Seed support up to INR 50L for incubated technology startups.",
    apply_url: "https://connect.acicvgu.com/programs/apply/nid8539/phase-3-call-for-application-nidhi-seed-support-program-ssp"
  },
  {
    name: "Toilet Board Coalition Accelerator 2027",
    type: "Accelerator",
    location: "Global",
    investments: null,
    sectors: ["Sanitation", "Climate", "Impact"],
    app_start: null,
    app_end: "2026-05-01",
    is_rolling: false,
    description: "12-month virtual accelerator for sanitation economy startups in emerging markets.",
    apply_url: "https://www.f6s.com/toilet-board-coalition-accelerator-2027/apply"
  },
  {
    name: "KrishiBoot - Pitch for Incubation",
    type: "Incubator",
    location: "India",
    investments: null,
    sectors: ["Agriculture", "AgriTech", "Incubation"],
    app_start: null,
    app_end: "2026-05-01",
    is_rolling: false,
    description: "Incubation pathway for early-stage agri startups and idea-stage founders.",
    apply_url: "https://aideanaarm.accubate.app/ext/form/23426/1/apply"
  },
  {
    name: "MG Developer Program and Grant Season 6.0",
    type: "Grants",
    location: "India",
    investments: null,
    sectors: ["Mobility", "Automotive", "Innovation"],
    app_start: null,
    app_end: "2026-05-01",
    is_rolling: false,
    description: "Innovation grant and program for mobility-focused startup solutions.",
    apply_url: "https://www.startupindia.gov.in/content/sih/en/ams-application/accelerator-program.html?applicationId=69ae994fe4b0b7e5b72b9dd4"
  },
  {
    name: "SBC Sprint2Frontier Acceleration Program 2026",
    type: "Accelerator",
    location: "India",
    investments: null,
    sectors: ["DeepTech", "Defense", "Climate", "AI"],
    app_start: null,
    app_end: "2026-05-01",
    is_rolling: false,
    description: "13-week accelerator for pre-Series A deeptech, defense, climate, and AI startups.",
    apply_url: "https://www.startupbootcamp.in/programs/sbc-sprint-2-launch-acceleration-program-2026"
  },
  {
    name: "IHFC-ARTPARK-Siemens MedTech Call 2026",
    type: "Grants",
    location: "India",
    investments: null,
    sectors: ["MedTech", "HealthTech", "Medical Devices"],
    app_start: null,
    app_end: "2026-05-01",
    is_rolling: false,
    description: "Grant support for startups solving defined medtech problem statements.",
    apply_url: "https://ihfc.accubate.app/ext/form/20720/1/apply"
  },
  {
    name: "PIEDS x 1811 Labs Gen AI Accelerator",
    type: "Accelerator",
    location: "India",
    investments: null,
    sectors: ["Generative AI", "AI", "B2B", "B2C"],
    app_start: null,
    app_end: "2026-05-01",
    is_rolling: false,
    description: "Three-month generative AI accelerator for MVP-stage startups.",
    apply_url: "https://pieds.accubate.app/ext/form/23485/1/apply"
  },
  {
    name: "Entrepreneurs First (EF) Bangalore Fall 26",
    type: "Incubator",
    location: "India",
    investments: null,
    sectors: ["DeepTech", "AI", "Founder Matching"],
    app_start: null,
    app_end: "2026-05-02",
    is_rolling: false,
    description: "EF Bangalore track for individuals building deeptech and AI startups from scratch.",
    apply_url: "https://apply.joinef.com/app/bangalore-fall/"
  },
  {
    name: "Peak XV Partners (ex-Sequoia India)",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["Tech", "Fintech", "Agnostic"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Zomato, Freshworks.",
    apply_url: "https://wep.gov.in/"
  },
  {
    name: "Accel India",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["SaaS", "Consumer", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Flipkart, Swiggy.",
    apply_url: "https://www.standupmitra.in/"
  },
  {
    name: "Lightspeed India",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["B2B", "EdTech", "Enterprise"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Multi-stage investor. Notable investments: Udaan, OYO.",
    apply_url: "https://www.mudra.org.in/"
  },
  {
    name: "Nexus Venture Partners",
    type: "VC",
    location: "Mumbai",
    market_scope: "India",
    investments: null,
    sectors: ["Enterprise SaaS", "AI"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Series A+ investor. Notable investments: Postman, Druva.",
    apply_url: "https://dcmsme.gov.in/schemes/Scheme_Women/TREAD.htm"
  },
  {
    name: "3one4 Capital",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["Fintech", "SaaS", "Consumer"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Licious, Jupiter.",
    apply_url: "https://seedfund.startupindia.gov.in/"
  },
  {
    name: "Blume Ventures",
    type: "VC",
    location: "Mumbai",
    market_scope: "India",
    investments: null,
    sectors: ["Tech", "Early-stage"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed and early-stage investor. Notable investments: Unacademy, GreyOrange.",
    apply_url: "https://www.dst.gov.in/kiran-women-scientist-scheme"
  },
  {
    name: "Elevation Capital (ex-SAIF)",
    type: "VC",
    location: "Gurugram",
    market_scope: "India",
    investments: null,
    sectors: ["Consumer", "Fintech", "SaaS"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth-focused investor. Notable investments: Meesho, Cure.fit.",
    apply_url: "https://birac.nic.in/"
  },
  {
    name: "Matrix Partners India",
    type: "VC",
    location: "Mumbai",
    market_scope: "India",
    investments: null,
    sectors: ["Consumer Tech", "B2B"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Early-stage investor. Notable investments: DailyHunt, Country Delight.",
    apply_url: "https://wehub.telangana.gov.in/"
  },
  {
    name: "Kalaari Capital",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["E-commerce", "Health"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Dream11, Cure.fit.",
    apply_url: "https://startupmission.kerala.gov.in/pages/women-startup"
  },
  {
    name: "100X.VC",
    type: "VC",
    location: "Mumbai",
    market_scope: "India",
    investments: null,
    sectors: ["Pre-seed", "Seed"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "First-cheque investor for early cohorts in India.",
    apply_url: "https://www.icreate.org.in/"
  },
  {
    name: "Chiratae Ventures",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["DeepTech", "AI", "Health"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Josh, Turtlemint.",
    apply_url: "https://www.startupkarnataka.in/"
  },
  {
    name: "Orios Venture Partners",
    type: "VC",
    location: "Mumbai",
    market_scope: "India",
    investments: null,
    sectors: ["Consumer Tech", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Early-stage investor. Notable investments: ShareChat, Goldset.",
    apply_url: "https://indiaai.gov.in/"
  },
  {
    name: "Stellaris Venture Partners",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["SaaS", "Fintech", "D2C"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to Series A investor. Notable investments: HealthifyMe, Goldset.",
    apply_url: "https://aicbanasthali.in/"
  },
  {
    name: "India Quotient",
    type: "VC",
    location: "Mumbai",
    market_scope: "India",
    investments: null,
    sectors: ["Consumer Internet", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed-stage investor. Notable investments: Urban Company, Mamaearth.",
    apply_url: "https://www.piedsbits.org/"
  },
  {
    name: "Fireside Ventures",
    type: "VC",
    location: "Mumbai",
    market_scope: "India",
    investments: null,
    sectors: ["D2C", "Consumer Brands"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Lenskart, Joy.",
    apply_url: "https://www.startupkarnataka.in/we-escalate"
  },
  {
    name: "Endiya Partners",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["DeepTech", "Enterprise"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Early-stage investor. Notable investments: Uniphore, Cropin.",
    apply_url: "https://www.startupindia.gov.in/content/sih/en/women_entrepreneurs.html"
  },
  {
    name: "DSG Consumer Partners",
    type: "VC",
    location: "Gurugram",
    market_scope: "India",
    investments: null,
    sectors: ["Food", "Consumer Brands"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Early-stage investor. Notable investments: Veeba, True Elements.",
    apply_url: "https://www.sidbi.in/en/products-and-services/direct-finance/mahila-udyam-nidhi"
  },
  {
    name: "Gemba Capital",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["Fintech", "SaaS"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Pre-seed and seed investor. Notable investments: Perfios, Perfico.",
    apply_url: "https://sbi.co.in/web/business/sme/sme-loans/stree-shakti-package"
  },
  {
    name: "Info Edge Ventures",
    type: "VC",
    location: "Noida",
    market_scope: "India",
    investments: null,
    sectors: ["Consumer Internet"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: Zomato, Naukri ecosystem bets.",
    apply_url: "https://nsfdc.nic.in/en/mahila-samriddhi-yojana"
  },
  {
    name: "Saama Capital",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["Tech", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth-stage investor. Notable investments: Mu Sigma, Perfios.",
    apply_url: "https://startupmission.kerala.gov.in/pages/women-startup"
  },
  {
    name: "Ankur Capital",
    type: "VC",
    location: "Mumbai",
    market_scope: "India",
    investments: null,
    sectors: ["DeepTech", "Health"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: Aindra Systems, Qure.ai.",
    apply_url: "https://wep.gov.in/"
  },
  {
    name: "Axilor Ventures",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["Tech", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed-stage investor. Notable investments: Ninjacart, HealthifyMe.",
    apply_url: "https://www.standupmitra.in/"
  },
  {
    name: "Aarin Capital",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["Enterprise", "Consumer"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Early-stage investor. Notable investments: Droom, GreyOrange.",
    apply_url: "https://www.mudra.org.in/"
  },
  {
    name: "Artha India Ventures",
    type: "VC",
    location: "Mumbai",
    market_scope: "India",
    investments: null,
    sectors: ["Fintech", "EdTech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: Finin, Eduvanz.",
    apply_url: "https://dcmsme.gov.in/schemes/Scheme_Women/TREAD.htm"
  },
  {
    name: "Bessemer Venture Partners",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["SaaS", "Cloud"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: Postman, Chargebee.",
    apply_url: "https://seedfund.startupindia.gov.in/"
  },
  {
    name: "Mayfield Fund",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["Enterprise", "AI"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Early-stage investor. Notable investments: Freshworks, Swiggy.",
    apply_url: "https://www.dst.gov.in/kiran-women-scientist-scheme"
  },
  {
    name: "Norwest Venture Partners",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["Health", "Consumer"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Multi-stage investor. Notable investments: Swiggy, Meesho.",
    apply_url: "https://birac.nic.in/"
  },
  {
    name: "General Catalyst",
    type: "VC",
    location: "Mumbai",
    market_scope: "India",
    investments: null,
    sectors: ["AI", "Climate"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: Khatabook, Captain Fresh.",
    apply_url: "https://wehub.telangana.gov.in/"
  },
  {
    name: "Jungle Ventures",
    type: "VC",
    location: "Singapore (India ops)",
    market_scope: "India",
    investments: null,
    sectors: ["Consumer", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor with India operations. Notable investments: Cloudnine, Livspace.",
    apply_url: "https://startupmission.kerala.gov.in/pages/women-startup"
  },
  {
    name: "Trifecta Capital",
    type: "VC",
    location: "Mumbai",
    market_scope: "India",
    investments: null,
    sectors: ["Credit", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: Alt Mobility, Progcap.",
    apply_url: "https://www.icreate.org.in/"
  },
  {
    name: "IvyCap Ventures",
    type: "VC",
    location: "Gurugram",
    market_scope: "India",
    investments: null,
    sectors: ["Tech", "Healthcare"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: Lenskart, OfBusiness.",
    apply_url: "https://www.startupkarnataka.in/"
  },
  {
    name: "Sixth Sense Ventures",
    type: "VC",
    location: "Mumbai",
    market_scope: "India",
    investments: null,
    sectors: ["Enterprise SaaS"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Early-stage investor. Notable investments: Innovaccer, GlobalLogic.",
    apply_url: "https://indiaai.gov.in/"
  },
  {
    name: "Steadview Capital",
    type: "VC",
    location: "Singapore (India ops)",
    market_scope: "India",
    investments: null,
    sectors: ["Fintech", "Consumer"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Late-stage investor with India operations. Notable investments: Meesho, PolicyBazaar.",
    apply_url: "https://aicbanasthali.in/"
  },
  {
    name: "Sistema Asia Capital",
    type: "VC",
    location: "Gurugram",
    market_scope: "India",
    investments: null,
    sectors: ["Tech", "Telecom"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: Pine Labs, LAVA.",
    apply_url: "https://www.piedsbits.org/"
  },
  {
    name: "Sprout Venture Partners",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["Logistics", "Health"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Early-stage investor. Notable investments: Delhivery, Practo.",
    apply_url: "https://www.startupkarnataka.in/we-escalate"
  },
  {
    name: "WEH Ventures",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["DeepTech", "Mobility"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: Ather Energy, Minus Zero.",
    apply_url: "https://www.startupindia.gov.in/content/sih/en/women_entrepreneurs.html"
  },
  {
    name: "YourNest Venture Capital",
    type: "VC",
    location: "Mumbai",
    market_scope: "India",
    investments: null,
    sectors: ["Hardware", "IoT"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: Miko, Emotibot.",
    apply_url: "https://www.sidbi.in/en/products-and-services/direct-finance/mahila-udyam-nidhi"
  },
  {
    name: "Zodius Capital",
    type: "VC",
    location: "Mumbai",
    market_scope: "India",
    investments: null,
    sectors: ["Consumer", "Enterprise"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Early-stage investor. Notable investments: Citrus Pay, Vee.",
    apply_url: "https://sbi.co.in/web/business/sme/sme-loans/stree-shakti-package"
  },
  {
    name: "Amicus Capital",
    type: "VC",
    location: "Chennai",
    market_scope: "India",
    investments: null,
    sectors: ["Financial Services"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: Satin Creditcare, MAS Financial.",
    apply_url: "https://nsfdc.nic.in/en/mahila-samriddhi-yojana"
  },
  {
    name: "Elevar Equity",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["Consumer Brands"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: Myntra, Lenskart.",
    apply_url: "https://startupmission.kerala.gov.in/pages/women-startup"
  },
  {
    name: "Gaja Capital",
    type: "VC",
    location: "Mumbai",
    market_scope: "India",
    investments: null,
    sectors: ["Education", "Financial"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: AU Small Finance, Lenskart.",
    apply_url: ""
  },
  {
    name: "GrowX Ventures",
    type: "VC",
    location: "Delhi",
    market_scope: "India",
    investments: null,
    sectors: ["EdTech", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Pre-seed investor. Notable investments: Eruditus, Classplus.",
    apply_url: ""
  },
  {
    name: "Inventus Capital Partners",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["SaaS", "Health"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: CleverTap, Innovaccer.",
    apply_url: ""
  },
  {
    name: "ITI Growth Opportunities Fund",
    type: "VC",
    location: "Mumbai",
    market_scope: "India",
    investments: null,
    sectors: ["Tech", "Consumer"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: Affle, Nazara.",
    apply_url: ""
  },
  {
    name: "Kae Capital",
    type: "VC",
    location: "Mumbai",
    market_scope: "India",
    investments: null,
    sectors: ["Tech-enabled Services"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Early-stage investor. Notable investments: 1Mg, Progcap.",
    apply_url: ""
  },
  {
    name: "Menterra Ventures",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["Impact", "Rural Tech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: Captain Fresh, GramCover.",
    apply_url: ""
  },
  {
    name: "Omnivore",
    type: "VC",
    location: "Mumbai",
    market_scope: "India",
    investments: null,
    sectors: ["AgriTech", "Food"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: DeHaat, WayCool.",
    apply_url: ""
  },
  {
    name: "Pravega Ventures",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["Enterprise", "Health"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: MyGate, Minddemic.",
    apply_url: ""
  },
  {
    name: "Quona Capital",
    type: "VC",
    location: "Washington (India ops)",
    market_scope: "India",
    investments: null,
    sectors: ["Fintech Inclusion"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Early-stage fintech investor with India operations. Notable investments: Scripbox, OkCredit.",
    apply_url: ""
  },
  {
    name: "Rockstud Capital",
    type: "VC",
    location: "Delhi",
    market_scope: "India",
    investments: null,
    sectors: ["Consumer Tech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: mCaffeine, GIVA.",
    apply_url: ""
  },
  {
    name: "Brand Capital",
    type: "VC",
    location: "Mumbai",
    market_scope: "India",
    investments: null,
    sectors: ["Media", "Consumer"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: boAt, Mamaearth.",
    apply_url: ""
  },
  {
    name: "EvoFund",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["Climate Tech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: BluSmart, Alt Mobility.",
    apply_url: ""
  },
  {
    name: "Eight Roads Ventures India",
    type: "VC",
    location: "Bengaluru",
    market_scope: "India",
    investments: null,
    sectors: ["Health", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Multi-stage investor. Notable investments: Pharmeasy, Acko.",
    apply_url: ""
  },
  {
    name: "General Atlantic India",
    type: "VC",
    location: "Mumbai",
    market_scope: "India",
    investments: null,
    sectors: ["Consumer", "Tech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Late-stage investor. Notable investments: Reliance Retail, Byju's.",
    apply_url: ""
  },
  {
    name: "Khosla Ventures India",
    type: "VC",
    location: "Menlo Park (India ops)",
    market_scope: "India",
    investments: null,
    sectors: ["Clean Tech", "AI"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Early-stage investor with India operations. Notable investments: Ola Electric, GreyOrange.",
    apply_url: ""
  },
  {
    name: "Menlo Ventures India",
    type: "VC",
    location: "Menlo Park (India ops)",
    market_scope: "India",
    investments: null,
    sectors: ["Enterprise Software"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor with India operations. Notable investments: Postman, 8i Ventures.",
    apply_url: ""
  },
  {
    name: "Naspers Internet Group",
    type: "VC",
    location: "Cape Town (India ops)",
    market_scope: "India",
    investments: null,
    sectors: ["E-commerce", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor with India operations. Notable investments: Flipkart, Swiggy.",
    apply_url: ""
  },
  {
    name: "Qualcomm Ventures India",
    type: "VC",
    location: "Noida",
    market_scope: "India",
    investments: null,
    sectors: ["Telecom", "IoT"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Early-stage investor. Notable investments: Reliance Jio, Infilect.",
    apply_url: ""
  },
  {
    name: "500 Global India",
    type: "VC",
    location: "San Francisco (India ops)",
    market_scope: "India",
    investments: null,
    sectors: ["Fintech", "SaaS"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor with India operations. Notable investments: Dunzo, HealthKart.",
    apply_url: ""
  },
  {
    name: "Sequoia Capital",
    type: "VC",
    location: "Menlo Park, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Consumer", "Enterprise", "Fintech", "AI"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Apple, Airbnb, Stripe.",
    apply_url: ""
  },
  {
    name: "Andreessen Horowitz",
    type: "VC",
    location: "Menlo Park, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["AI", "Crypto", "Consumer", "Enterprise"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to late-stage investor. Notable investments: Facebook, Coinbase, GitHub.",
    apply_url: ""
  },
  {
    name: "Accel (Global)",
    type: "VC",
    location: "Palo Alto, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Consumer Internet", "Enterprise Software", "AI"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Facebook, Slack, Atlassian.",
    apply_url: ""
  },
  {
    name: "Benchmark",
    type: "VC",
    location: "San Francisco, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Marketplaces", "Software", "AI"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to early growth investor. Notable investments: Uber, Twitter, Zillow.",
    apply_url: ""
  },
  {
    name: "Kleiner Perkins",
    type: "VC",
    location: "Menlo Park, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["AI", "Health", "Climate", "Enterprise"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Google, Amazon, Genentech.",
    apply_url: ""
  },
  {
    name: "Lightspeed Venture Partners",
    type: "VC",
    location: "Menlo Park, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Consumer", "Enterprise", "Fintech", "AI"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Snap, Nest, Epic Games.",
    apply_url: ""
  },
  {
    name: "Tiger Global Management",
    type: "VC",
    location: "New York, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Internet", "Software", "Consumer", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: Stripe, Facebook, Flipkart.",
    apply_url: ""
  },
  {
    name: "Greylock Partners",
    type: "VC",
    location: "Menlo Park, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Enterprise Software", "Consumer", "Cybersecurity"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: LinkedIn, Airbnb, Discord.",
    apply_url: ""
  },
  {
    name: "Bessemer Venture Partners (Global)",
    type: "VC",
    location: "New York, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Cloud", "AI", "Fintech", "Healthcare"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Shopify, LinkedIn, Twilio.",
    apply_url: ""
  },
  {
    name: "NEA",
    type: "VC",
    location: "Menlo Park, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Software", "Healthcare", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Robinhood, Coursera, Databricks.",
    apply_url: ""
  },
  {
    name: "Founders Fund",
    type: "VC",
    location: "San Francisco, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["AI", "Defense Tech", "Biotech", "Software"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to late-stage investor. Notable investments: SpaceX, Palantir, Airbnb.",
    apply_url: ""
  },
  {
    name: "General Catalyst (Global)",
    type: "VC",
    location: "San Francisco, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["AI", "Healthcare", "Consumer", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Stripe, Snap, Gusto.",
    apply_url: ""
  },
  {
    name: "Index Ventures",
    type: "VC",
    location: "London / San Francisco",
    market_scope: "Global",
    investments: null,
    sectors: ["Software", "Fintech", "Security", "Commerce"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Dropbox, Slack, Revolut.",
    apply_url: ""
  },
  {
    name: "GV",
    type: "VC",
    location: "Mountain View, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["AI", "Life Sciences", "Enterprise", "Cloud"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Uber, Stripe, Slack.",
    apply_url: ""
  },
  {
    name: "Union Square Ventures",
    type: "VC",
    location: "New York, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Internet", "Climate", "Crypto", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to early growth investor. Notable investments: Twitter, Coinbase, Etsy.",
    apply_url: ""
  },
  {
    name: "First Round Capital",
    type: "VC",
    location: "San Francisco, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Seed", "Software", "Consumer", "AI"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: Notion, Uber, Square.",
    apply_url: ""
  },
  {
    name: "Ribbit Capital",
    type: "VC",
    location: "Palo Alto, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Fintech", "Insurance", "Payments", "Crypto"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Robinhood, Nubank, Coinbase.",
    apply_url: ""
  },
  {
    name: "Menlo Ventures (Global)",
    type: "VC",
    location: "Menlo Park, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["AI", "Cybersecurity", "Enterprise Software"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Anthropic, Siri, Roku.",
    apply_url: ""
  },
  {
    name: "CRV",
    type: "VC",
    location: "San Francisco, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Dev Tools", "Enterprise", "Consumer Internet"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to Series A investor. Notable investments: DoorDash, Notion, Zendesk.",
    apply_url: ""
  },
  {
    name: "Sequoia Capital China",
    type: "VC",
    location: "Beijing, China",
    market_scope: "Global",
    investments: null,
    sectors: ["Consumer", "Enterprise", "Fintech", "AI"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: ByteDance, Pinduoduo, Meituan.",
    apply_url: ""
  },
  {
    name: "Dragonfly Capital",
    type: "VC",
    location: "Singapore",
    market_scope: "Global",
    investments: null,
    sectors: ["Crypto", "Web3", "Fintech Infrastructure"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Avalanche, Maker, Clearpool.",
    apply_url: ""
  },
  {
    name: "SoftBank Vision Fund",
    type: "VC",
    location: "Tokyo, Japan",
    market_scope: "Global",
    investments: null,
    sectors: ["AI", "Mobility", "Enterprise", "Consumer"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: Uber, WeWork, Coupang.",
    apply_url: ""
  },
  {
    name: "DST Global",
    type: "VC",
    location: "London, UK",
    market_scope: "Global",
    investments: null,
    sectors: ["Internet", "Consumer", "Fintech", "Software"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: Facebook, Twitter, Spotify.",
    apply_url: ""
  },
  {
    name: "Coatue",
    type: "VC",
    location: "New York, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Software", "Internet", "Fintech", "AI"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: Snowflake, DoorDash, ByteDance.",
    apply_url: ""
  },
  {
    name: "Insight Partners",
    type: "VC",
    location: "New York, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Software", "Cybersecurity", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: Wiz, monday.com, Spotify.",
    apply_url: ""
  },
  {
    name: "Khosla Ventures (Global)",
    type: "VC",
    location: "Menlo Park, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["AI", "Climate", "Biotech", "Software"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: OpenAI, DoorDash, Square.",
    apply_url: ""
  },
  {
    name: "Matrix Partners (Global)",
    type: "VC",
    location: "San Francisco, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Consumer", "Enterprise", "Fintech", "SaaS"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: HubSpot, Canva, Postman.",
    apply_url: ""
  },
  {
    name: "Redpoint Ventures",
    type: "VC",
    location: "Menlo Park, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Consumer", "Cloud", "Infrastructure", "AI"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Stripe, Snowflake, Twilio.",
    apply_url: ""
  },
  {
    name: "Sapphire Ventures",
    type: "VC",
    location: "Austin, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Enterprise Software", "Cloud", "AI"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Series A to growth investor. Notable investments: MuleSoft, DocuSign, ThoughtSpot.",
    apply_url: ""
  },
  {
    name: "Felicis",
    type: "VC",
    location: "Menlo Park, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["AI", "Security", "Developer Tools", "Consumer"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Shopify, Fitbit, Notion.",
    apply_url: ""
  },
  {
    name: "True Ventures",
    type: "VC",
    location: "Palo Alto, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Consumer Software", "Climate", "Crypto"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: Fitbit, Peloton, Automattic.",
    apply_url: ""
  },
  {
    name: "Y Combinator (Fund)",
    type: "VC",
    location: "Mountain View, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Software", "AI", "Consumer", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Pre-seed to seed investor. Notable investments: Airbnb, Dropbox, Stripe.",
    apply_url: ""
  },
  {
    name: "Techstars (Fund)",
    type: "VC",
    location: "Boulder, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Fintech", "HealthTech", "AgTech", "Climate Tech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: SendGrid, ClassPass, PillPack.",
    apply_url: ""
  },
  {
    name: "SOSV",
    type: "VC",
    location: "Princeton, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Deep Tech", "Climate", "Biotech", "Hardware"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Pre-seed to seed investor. Notable investments: Perfect Day, NotCo, Humatics.",
    apply_url: ""
  },
  {
    name: "500 Global (Fund)",
    type: "VC",
    location: "San Francisco, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["AI", "Fintech", "E-commerce", "SaaS"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to early growth investor. Notable investments: Canva, Grab, Udemy.",
    apply_url: ""
  },
  {
    name: "Plug and Play Ventures",
    type: "VC",
    location: "Sunnyvale, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Fintech", "Mobility", "IoT", "Health"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: PayPal, Dropbox, Honey.",
    apply_url: ""
  },
  {
    name: "Pear VC",
    type: "VC",
    location: "San Francisco, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Software", "Fintech", "Consumer", "AI"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: Deel, Mercury, Lattice.",
    apply_url: ""
  },
  {
    name: "Initialized Capital",
    type: "VC",
    location: "San Francisco, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Seed", "Software", "Consumer", "Crypto"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: Coinbase, Instacart, Rippling.",
    apply_url: ""
  },
  {
    name: "Kindred Ventures",
    type: "VC",
    location: "San Francisco, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Seed", "AI", "Fintech", "Consumer"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: Uber, Patreon, Stripe.",
    apply_url: ""
  },
  {
    name: "Homebrew",
    type: "VC",
    location: "San Francisco, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Developer Tools", "Fintech", "SaaS"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: Chime, Gusto, Plaid.",
    apply_url: ""
  },
  {
    name: "Forerunner Ventures",
    type: "VC",
    location: "San Francisco, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Consumer", "Commerce", "Marketplaces"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Warby Parker, Glossier, Chime.",
    apply_url: ""
  },
  {
    name: "Spark Capital",
    type: "VC",
    location: "San Francisco, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Consumer", "Media", "Software"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Twitter, Anthropic, Slack.",
    apply_url: ""
  },
  {
    name: "Thrive Capital (Global)",
    type: "VC",
    location: "New York, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Software", "AI", "Internet", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: OpenAI, Stripe, Instagram.",
    apply_url: ""
  },
  {
    name: "Goldman Sachs Growth",
    type: "VC",
    location: "New York, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Fintech", "Software", "Enterprise"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: Stripe, Wefox, Klarna.",
    apply_url: ""
  },
  {
    name: "TCV",
    type: "VC",
    location: "Palo Alto, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Consumer Internet", "Software", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: Netflix, Spotify, Airbnb.",
    apply_url: ""
  },
  {
    name: "General Atlantic",
    type: "VC",
    location: "New York, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Consumer", "Technology", "Healthcare"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Late-stage investor. Notable investments: Airbnb, Slack, ByteDance.",
    apply_url: ""
  },
  {
    name: "Canaan Partners",
    type: "VC",
    location: "Menlo Park, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Seed", "Healthcare", "Enterprise", "Consumer"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Splunk, LendingClub, Instacart.",
    apply_url: ""
  },
  {
    name: "IVP",
    type: "VC",
    location: "Menlo Park, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Late-stage Software", "Internet", "AI"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: Twitter, Dropbox, Snapchat.",
    apply_url: ""
  },
  {
    name: "Scale Venture Partners",
    type: "VC",
    location: "Foster City, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["SaaS", "AI", "Cloud Infrastructure"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: HubSpot, DocuSign, Box.",
    apply_url: ""
  },
  {
    name: "Social Capital",
    type: "VC",
    location: "Palo Alto, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["AI", "Education", "Health", "Enterprise"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Slack, SurveyMonkey, Intercom.",
    apply_url: ""
  },
  {
    name: "GGV Capital",
    type: "VC",
    location: "San Francisco, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Consumer", "Enterprise", "Fintech", "AI"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Slack, Opendoor, Wish.",
    apply_url: ""
  },
  {
    name: "AME Cloud Ventures",
    type: "VC",
    location: "Palo Alto, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Cloud", "Infrastructure", "AI", "Data"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Uber, Twilio, Flexport.",
    apply_url: ""
  },
  {
    name: "Bloomberg Beta",
    type: "VC",
    location: "San Francisco, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Future of Work", "AI", "Software", "Data"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: Slack, Asana, Figma.",
    apply_url: ""
  },
  {
    name: "Craft Ventures",
    type: "VC",
    location: "San Francisco, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["SaaS", "Cloud", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Zoom, ClickUp, Pave.",
    apply_url: ""
  },
  {
    name: "Norwest Venture Partners (Global)",
    type: "VC",
    location: "San Francisco, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Enterprise", "Consumer", "Healthcare"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Uber, Nutanix, Calm.",
    apply_url: ""
  },
  {
    name: "Accel-KKR",
    type: "VC",
    location: "Menlo Park, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Software", "IT", "B2B Services"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: Sage Intacct, Personio, Onit.",
    apply_url: ""
  },
  {
    name: "Shasta Ventures",
    type: "VC",
    location: "Menlo Park, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Enterprise", "Cloud", "Consumer"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to Series A investor. Notable investments: Firebase, Zuora, Twist.",
    apply_url: ""
  },
  {
    name: "Madrona Venture Group",
    type: "VC",
    location: "Seattle, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["AI", "Cloud", "Software", "Commerce"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Snowflake, Smartsheet, Rover.",
    apply_url: ""
  },
  {
    name: "Wing Venture Capital",
    type: "VC",
    location: "Palo Alto, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Enterprise Software", "AI", "Cloud"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Cohesity, Gong, Snowflake.",
    apply_url: ""
  },
  {
    name: "Balderton Capital",
    type: "VC",
    location: "London, UK",
    market_scope: "Global",
    investments: null,
    sectors: ["SaaS", "Fintech", "Health", "Marketplaces"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Revolut, Depop, DuckDuckGo.",
    apply_url: ""
  },
  {
    name: "Atomico",
    type: "VC",
    location: "London, UK",
    market_scope: "Global",
    investments: null,
    sectors: ["Software", "AI", "Climate", "Gaming"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Klarna, Supercell, Lilium.",
    apply_url: ""
  },
  {
    name: "LocalGlobe",
    type: "VC",
    location: "London, UK",
    market_scope: "Global",
    investments: null,
    sectors: ["Consumer", "SaaS", "Deep Tech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Pre-seed to seed investor. Notable investments: Monzo, Wise, Freetrade.",
    apply_url: ""
  },
  {
    name: "Octopus Ventures",
    type: "VC",
    location: "London, UK",
    market_scope: "Global",
    investments: null,
    sectors: ["Health", "Fintech", "Deep Tech", "Consumer"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Depop, Cazoo, Shieldpay.",
    apply_url: ""
  },
  {
    name: "MMC Ventures",
    type: "VC",
    location: "London, UK",
    market_scope: "Global",
    investments: null,
    sectors: ["SaaS", "AI", "Fintech", "Data"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to Series A investor. Notable investments: Gousto, Snyk, Signal AI.",
    apply_url: ""
  },
  {
    name: "Dawn Capital",
    type: "VC",
    location: "London, UK",
    market_scope: "Global",
    investments: null,
    sectors: ["Enterprise Software", "Data", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Mimecast, Tink, iZettle.",
    apply_url: ""
  },
  {
    name: "Creandum",
    type: "VC",
    location: "Stockholm, Sweden",
    market_scope: "Global",
    investments: null,
    sectors: ["Software", "Fintech", "Consumer", "Climate"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Spotify, Klarna, Lunar.",
    apply_url: ""
  },
  {
    name: "Northzone",
    type: "VC",
    location: "London / Stockholm",
    market_scope: "Global",
    investments: null,
    sectors: ["Consumer", "Fintech", "Health", "SaaS"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Spotify, Klarna, Truecaller.",
    apply_url: ""
  },
  {
    name: "Point Nine",
    type: "VC",
    location: "Berlin, Germany",
    market_scope: "Global",
    investments: null,
    sectors: ["SaaS", "Marketplaces", "Developer Tools"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: Zendesk, Delivery Hero, Loom.",
    apply_url: ""
  },
  {
    name: "Lakestar",
    type: "VC",
    location: "Zurich, Switzerland",
    market_scope: "Global",
    investments: null,
    sectors: ["AI", "Fintech", "Health", "Consumer"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Spotify, Revolut, Skype.",
    apply_url: ""
  },
  {
    name: "HV Capital",
    type: "VC",
    location: "Munich, Germany",
    market_scope: "Global",
    investments: null,
    sectors: ["Internet", "Software", "Fintech", "Climate"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Zalando, Flix, SumUp.",
    apply_url: ""
  },
  {
    name: "EQT Ventures",
    type: "VC",
    location: "Stockholm, Sweden",
    market_scope: "Global",
    investments: null,
    sectors: ["Software", "Climate", "Mobility", "AI"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Wolt, Juni, Klarna.",
    apply_url: ""
  },
  {
    name: "Cherry Ventures",
    type: "VC",
    location: "Berlin, Germany",
    market_scope: "Global",
    investments: null,
    sectors: ["SaaS", "Fintech", "Consumer", "Deep Tech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to Series A investor. Notable investments: FlixBus, Auto1, Forto.",
    apply_url: ""
  },
  {
    name: "Target Global",
    type: "VC",
    location: "Berlin, Germany",
    market_scope: "Global",
    investments: null,
    sectors: ["Consumer", "Fintech", "SaaS", "Mobility"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Delivery Hero, Catawiki, WeFox.",
    apply_url: ""
  },
  {
    name: "Earlybird Venture Capital",
    type: "VC",
    location: "Berlin, Germany",
    market_scope: "Global",
    investments: null,
    sectors: ["SaaS", "Fintech", "Health", "Deep Tech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: UiPath, N26, Smava.",
    apply_url: ""
  },
  {
    name: "Notion Capital",
    type: "VC",
    location: "London, UK",
    market_scope: "Global",
    investments: null,
    sectors: ["Cloud", "SaaS", "Fintech", "AI"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: GoCardless, Mews, Paddle.",
    apply_url: ""
  },
  {
    name: "83North",
    type: "VC",
    location: "London / Tel Aviv",
    market_scope: "Global",
    investments: null,
    sectors: ["Enterprise", "Consumer", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Guardicore, Just Eat, Wolt.",
    apply_url: ""
  },
  {
    name: "Partech",
    type: "VC",
    location: "Paris, France",
    market_scope: "Global",
    investments: null,
    sectors: ["Software", "Fintech", "Mobility", "Deep Tech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Alan, Made.com, Sorare.",
    apply_url: ""
  },
  {
    name: "Alven",
    type: "VC",
    location: "Paris, France",
    market_scope: "Global",
    investments: null,
    sectors: ["SaaS", "Marketplaces", "Fintech", "AI"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: ManoMano, Qonto, Shift Technology.",
    apply_url: ""
  },
  {
    name: "Elaia",
    type: "VC",
    location: "Paris, France",
    market_scope: "Global",
    investments: null,
    sectors: ["Deep Tech", "Software", "Cybersecurity"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Criteo, Mirakl, Shift Technology.",
    apply_url: ""
  },
  {
    name: "Daphni",
    type: "VC",
    location: "Paris, France",
    market_scope: "Global",
    investments: null,
    sectors: ["Consumer", "AI", "Climate", "Mobility"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Back Market, Lydia, Hubcycle.",
    apply_url: ""
  },
  {
    name: "Sofina",
    type: "VC",
    location: "Brussels, Belgium",
    market_scope: "Global",
    investments: null,
    sectors: ["Consumer", "Internet", "Healthcare", "Education"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: Byju's, Swiggy, Spotify.",
    apply_url: ""
  },
  {
    name: "Kima Ventures",
    type: "VC",
    location: "Paris, France",
    market_scope: "Global",
    investments: null,
    sectors: ["Internet", "SaaS", "Fintech", "Consumer"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: Telegram, Algolia, Front.",
    apply_url: ""
  },
  {
    name: "Idinvest Partners",
    type: "VC",
    location: "Paris, France",
    market_scope: "Global",
    investments: null,
    sectors: ["SaaS", "Fintech", "Healthcare", "Impact"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Scality, BoondManager, Believe.",
    apply_url: ""
  },
  {
    name: "Index Ventures Europe",
    type: "VC",
    location: "London / San Francisco",
    market_scope: "Global",
    investments: null,
    sectors: ["Software", "Fintech", "Security", "Commerce"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Dropbox, Slack, Revolut.",
    apply_url: ""
  },
  {
    name: "Peak Capital",
    type: "VC",
    location: "Amsterdam, Netherlands",
    market_scope: "Global",
    investments: null,
    sectors: ["SaaS", "Marketplaces", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Typeform, Pitch, Acast.",
    apply_url: ""
  },
  {
    name: "Endeit Capital",
    type: "VC",
    location: "Amsterdam, Netherlands",
    market_scope: "Global",
    investments: null,
    sectors: ["Enterprise Software", "Fintech", "Commerce"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Growth investor. Notable investments: Helloprint, Scalable Capital.",
    apply_url: ""
  },
  {
    name: "RTP Global",
    type: "VC",
    location: "London / New York",
    market_scope: "Global",
    investments: null,
    sectors: ["Software", "AI", "Fintech", "Marketplaces"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Delivery Hero, Datadog, Cred.",
    apply_url: ""
  },
  {
    name: "Almaz Capital",
    type: "VC",
    location: "Palo Alto, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Enterprise", "Cloud", "Deep Tech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Acumatica, UiPath, StarWind.",
    apply_url: ""
  },
  {
    name: "Flint Capital",
    type: "VC",
    location: "Boston, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["AI", "Fintech", "Cybersecurity"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: AppsFlyer, DoubleVerify, Lemonade.",
    apply_url: ""
  },
  {
    name: "RTP Ventures",
    type: "VC",
    location: "New York, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Software", "AI", "Fintech"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Coursera, Vanta, Paradox.",
    apply_url: ""
  },
  {
    name: "GSV Ventures",
    type: "VC",
    location: "San Francisco, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["EdTech", "Future of Work", "AI"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Coursera, ClassDojo, MasterClass.",
    apply_url: ""
  },
  {
    name: "B Capital",
    type: "VC",
    location: "Los Angeles, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Enterprise", "Fintech", "Healthcare"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Bird, Evidation, Ninja Van.",
    apply_url: ""
  },
  {
    name: "Goodwater Capital",
    type: "VC",
    location: "Menlo Park, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Consumer Internet", "Fintech", "Health"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Spotify, Klook, Robinhood.",
    apply_url: ""
  },
  {
    name: "Owl Ventures",
    type: "VC",
    location: "Palo Alto, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["EdTech", "Workforce", "Learning Tools"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Coursera, Duolingo, Outschool.",
    apply_url: ""
  },
  {
    name: "Canvas Ventures",
    type: "VC",
    location: "Menlo Park, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Fintech", "Health", "Enterprise", "Consumer"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Plaid, Branch, Upgrade.",
    apply_url: ""
  },
  {
    name: "Cowboy Ventures",
    type: "VC",
    location: "Palo Alto, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Enterprise", "Consumer", "Fintech", "Developer Tools"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed investor. Notable investments: SentinelOne, Dollar Shave Club, Monzo.",
    apply_url: ""
  },
  {
    name: "SignalFire",
    type: "VC",
    location: "San Francisco, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["AI", "B2B Software", "Data", "Healthcare"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Frame.io, Grammarly, Noom.",
    apply_url: ""
  },
  {
    name: "Lux Capital",
    type: "VC",
    location: "New York, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["Deep Tech", "Biotech", "AI", "Robotics"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Seed to growth investor. Notable investments: Anduril, Zoox, Color.",
    apply_url: ""
  },
  {
    name: "Contrary Capital",
    type: "VC",
    location: "San Francisco, USA",
    market_scope: "Global",
    investments: null,
    sectors: ["AI", "Developer Tools", "Enterprise", "Consumer"],
    app_start: null,
    app_end: null,
    is_rolling: true,
    description: "Pre-seed to seed investor. Notable investments: Anduril, Ramp, Zepto.",
    apply_url: "https://www.contrary.com/"
  }
];
